// Code generated by goyacc -o parser/parser.go -v parser/parser.output parser/parser.go.y. DO NOT EDIT.

//line parser/parser.go.y:2
package parser

import __yyfmt__ "fmt"

//line parser/parser.go.y:2

//line parser/parser.go.y:5
type yySymType struct {
	yys     int
	integer int
	symbol  string
}

const NUMBER = 57346
const ID = 57347
const STRING = 57348
const EMAIL = 57349
const IPV4 = 57350
const IPV6 = 57351
const IP_CIDR = 57352
const IPADDR_RANGE = 57353
const HEX32 = 57354
const PATHSTR = 57355
const LB = 57356
const RB = 57357
const GLOBALDEFS = 57358
const NOTIFICATION_EMAIL = 57359
const NOTIFICATION_EMAIL_FROM = 57360
const SMTP_SERVER = 57361
const SMTP_CONNECT_TIMEOUT = 57362
const ROUTER_ID = 57363
const LVS_ID = 57364
const VRRP_MCAST_GROUP4 = 57365
const VRRP_MCAST_GROUP6 = 57366
const VRRP_GARP_MASTER_DELAY = 57367
const VRRP_GARP_MASTER_REPEAT = 57368
const VRRP_GARP_MASTER_REFRESH = 57369
const VRRP_GARP_MASTER_REFRESH_REPEAT = 57370
const VRRP_VERSION = 57371
const ENABLE_SCRIPT_SECURITY = 57372
const STATIC_IPADDRESS = 57373
const STATIC_ROUTES = 57374
const STATIC_RULES = 57375
const VRRP_SYNC_GROUP = 57376
const GROUP = 57377
const VRRP_INSTANCE = 57378
const USE_VMAC = 57379
const VERSION = 57380
const VMAC_XMIT_BASE = 57381
const NATIVE_IPV6 = 57382
const INTERFACE = 57383
const MCAST_SRC_IP = 57384
const UNICAST_SRC_IP = 57385
const UNICAST_PEER = 57386
const LVS_SYNC_DAEMON_INTERFACE = 57387
const VIRTUAL_ROUTER_ID = 57388
const NOPREEMPT = 57389
const PREEMPT_DELAY = 57390
const PRIORITY = 57391
const ADVERT_INT = 57392
const VIRTUAL_IPADDRESS = 57393
const VIRTUAL_IPADDRESS_EXCLUDED = 57394
const VIRTUAL_ROUTES = 57395
const STATE = 57396
const MASTER = 57397
const BACKUP = 57398
const GARP_MASTER_DELAY = 57399
const SMTP_ALERT = 57400
const AUTHENTICATION = 57401
const AUTH_TYPE = 57402
const AUTH_PASS = 57403
const PASS = 57404
const AH = 57405
const LABEL = 57406
const DEV = 57407
const SCOPE = 57408
const SITE = 57409
const LINK = 57410
const HOST = 57411
const NOWHERE = 57412
const GLOBAL = 57413
const BRD = 57414
const SRC = 57415
const FROM = 57416
const TO = 57417
const VIA = 57418
const GW = 57419
const OR = 57420
const TABLE = 57421
const METRIC = 57422
const TRACK_INTERFACE = 57423
const TRACK_SCRIPT = 57424
const DONT_TRACK_PRIMARY = 57425
const NOTIFY_MASTER = 57426
const NOTIFY_BACKUP = 57427
const NOTIFY_FAULT = 57428
const NOTIFY_STOP = 57429
const NOTIFY = 57430
const BLACKHOLE = 57431
const VRRP_SCRIPT = 57432
const SCRIPT = 57433
const INTERVAL = 57434
const TIMEOUT = 57435
const WEIGHT = 57436
const FALL = 57437
const RISE = 57438
const VIRTUAL_SERVER_GROUP = 57439
const VIRTUAL_SERVER = 57440
const DELAY_LOOP = 57441
const LB_ALGO = 57442
const LB_KIND = 57443
const LVS_SCHED = 57444
const LVS_METHOD = 57445
const RR = 57446
const WRR = 57447
const LC = 57448
const WLC = 57449
const FO = 57450
const OVF = 57451
const LBLC = 57452
const LBLCR = 57453
const SH = 57454
const DH = 57455
const SED = 57456
const NQ = 57457
const NAT = 57458
const DR = 57459
const TUN = 57460
const PERSISTENCE_TIMEOUT = 57461
const PROTOCOL = 57462
const TCP = 57463
const UDP = 57464
const SORRY_SERVER = 57465
const REAL_SERVER = 57466
const FWMARK = 57467
const INHIBIT_ON_FAILURE = 57468
const TCP_CHECK = 57469
const HTTP_GET = 57470
const SSL_GET = 57471
const SMTP_CHECK = 57472
const DNS_CHECK = 57473
const MISC_CHECK = 57474
const URL = 57475
const PATH = 57476
const DIGEST = 57477
const STATUS_CODE = 57478
const CONNECT_TIMEOUT = 57479
const CONNECT_PORT = 57480
const CONNECT_IP = 57481
const BINDTO = 57482
const BIND_PORT = 57483
const RETRY = 57484
const HELO_NAME = 57485
const TYPE = 57486
const NAME = 57487
const MISC_PATH = 57488
const MISC_TIMEOUT = 57489
const WARMUP = 57490
const MISC_DYNAMIC = 57491
const NB_GET_RETRY = 57492
const DELAY_BEFORE_RETRY = 57493
const VIRTUALHOST = 57494
const ALPHA = 57495
const OMEGA = 57496
const QUORUM = 57497
const HYSTERESIS = 57498
const QUORUM_UP = 57499
const QUORUM_DOWN = 57500

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUMBER",
	"ID",
	"STRING",
	"EMAIL",
	"IPV4",
	"IPV6",
	"IP_CIDR",
	"IPADDR_RANGE",
	"HEX32",
	"PATHSTR",
	"LB",
	"RB",
	"GLOBALDEFS",
	"NOTIFICATION_EMAIL",
	"NOTIFICATION_EMAIL_FROM",
	"SMTP_SERVER",
	"SMTP_CONNECT_TIMEOUT",
	"ROUTER_ID",
	"LVS_ID",
	"VRRP_MCAST_GROUP4",
	"VRRP_MCAST_GROUP6",
	"VRRP_GARP_MASTER_DELAY",
	"VRRP_GARP_MASTER_REPEAT",
	"VRRP_GARP_MASTER_REFRESH",
	"VRRP_GARP_MASTER_REFRESH_REPEAT",
	"VRRP_VERSION",
	"ENABLE_SCRIPT_SECURITY",
	"STATIC_IPADDRESS",
	"STATIC_ROUTES",
	"STATIC_RULES",
	"VRRP_SYNC_GROUP",
	"GROUP",
	"VRRP_INSTANCE",
	"USE_VMAC",
	"VERSION",
	"VMAC_XMIT_BASE",
	"NATIVE_IPV6",
	"INTERFACE",
	"MCAST_SRC_IP",
	"UNICAST_SRC_IP",
	"UNICAST_PEER",
	"LVS_SYNC_DAEMON_INTERFACE",
	"VIRTUAL_ROUTER_ID",
	"NOPREEMPT",
	"PREEMPT_DELAY",
	"PRIORITY",
	"ADVERT_INT",
	"VIRTUAL_IPADDRESS",
	"VIRTUAL_IPADDRESS_EXCLUDED",
	"VIRTUAL_ROUTES",
	"STATE",
	"MASTER",
	"BACKUP",
	"GARP_MASTER_DELAY",
	"SMTP_ALERT",
	"AUTHENTICATION",
	"AUTH_TYPE",
	"AUTH_PASS",
	"PASS",
	"AH",
	"LABEL",
	"DEV",
	"SCOPE",
	"SITE",
	"LINK",
	"HOST",
	"NOWHERE",
	"GLOBAL",
	"BRD",
	"SRC",
	"FROM",
	"TO",
	"VIA",
	"GW",
	"OR",
	"TABLE",
	"METRIC",
	"TRACK_INTERFACE",
	"TRACK_SCRIPT",
	"DONT_TRACK_PRIMARY",
	"NOTIFY_MASTER",
	"NOTIFY_BACKUP",
	"NOTIFY_FAULT",
	"NOTIFY_STOP",
	"NOTIFY",
	"BLACKHOLE",
	"VRRP_SCRIPT",
	"SCRIPT",
	"INTERVAL",
	"TIMEOUT",
	"WEIGHT",
	"FALL",
	"RISE",
	"VIRTUAL_SERVER_GROUP",
	"VIRTUAL_SERVER",
	"DELAY_LOOP",
	"LB_ALGO",
	"LB_KIND",
	"LVS_SCHED",
	"LVS_METHOD",
	"RR",
	"WRR",
	"LC",
	"WLC",
	"FO",
	"OVF",
	"LBLC",
	"LBLCR",
	"SH",
	"DH",
	"SED",
	"NQ",
	"NAT",
	"DR",
	"TUN",
	"PERSISTENCE_TIMEOUT",
	"PROTOCOL",
	"TCP",
	"UDP",
	"SORRY_SERVER",
	"REAL_SERVER",
	"FWMARK",
	"INHIBIT_ON_FAILURE",
	"TCP_CHECK",
	"HTTP_GET",
	"SSL_GET",
	"SMTP_CHECK",
	"DNS_CHECK",
	"MISC_CHECK",
	"URL",
	"PATH",
	"DIGEST",
	"STATUS_CODE",
	"CONNECT_TIMEOUT",
	"CONNECT_PORT",
	"CONNECT_IP",
	"BINDTO",
	"BIND_PORT",
	"RETRY",
	"HELO_NAME",
	"TYPE",
	"NAME",
	"MISC_PATH",
	"MISC_TIMEOUT",
	"WARMUP",
	"MISC_DYNAMIC",
	"NB_GET_RETRY",
	"DELAY_BEFORE_RETRY",
	"VIRTUALHOST",
	"ALPHA",
	"OMEGA",
	"QUORUM",
	"HYSTERESIS",
	"QUORUM_UP",
	"QUORUM_DOWN",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/parser.go.y:382

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 19,
	14, 128,
	-2, 298,
	-1, 203,
	15, 120,
	-2, 121,
}

const yyPrivate = 57344

const yyLast = 559

var yyAct = [...]int{

	410, 490, 485, 64, 433, 422, 408, 399, 392, 371,
	336, 332, 209, 328, 183, 315, 321, 313, 311, 30,
	308, 184, 207, 33, 202, 280, 175, 55, 267, 185,
	34, 35, 65, 401, 60, 144, 411, 402, 403, 288,
	289, 395, 394, 487, 488, 489, 396, 136, 406, 96,
	404, 405, 397, 367, 61, 398, 34, 35, 55, 205,
	219, 106, 435, 436, 437, 438, 116, 117, 498, 334,
	119, 120, 121, 281, 282, 283, 34, 35, 128, 218,
	217, 132, 134, 216, 492, 75, 70, 69, 73, 53,
	204, 61, 421, 214, 479, 62, 115, 63, 66, 67,
	68, 71, 72, 32, 420, 417, 416, 418, 419, 413,
	415, 74, 359, 360, 429, 412, 77, 78, 414, 330,
	331, 186, 187, 188, 189, 190, 428, 425, 424, 426,
	427, 430, 373, 431, 432, 421, 108, 468, 34, 35,
	320, 191, 192, 12, 105, 193, 194, 420, 417, 416,
	418, 419, 243, 244, 455, 231, 232, 335, 13, 14,
	15, 16, 131, 17, 374, 375, 376, 377, 378, 379,
	380, 454, 37, 206, 195, 196, 197, 198, 199, 200,
	201, 228, 34, 35, 65, 221, 177, 178, 179, 180,
	181, 182, 446, 31, 316, 317, 439, 290, 291, 264,
	138, 391, 318, 256, 382, 365, 457, 204, 362, 448,
	127, 88, 214, 357, 355, 61, 285, 18, 284, 351,
	265, 346, 344, 342, 20, 19, 302, 297, 298, 139,
	263, 303, 34, 35, 56, 255, 227, 312, 70, 69,
	73, 34, 35, 320, 319, 319, 220, 62, 247, 63,
	66, 67, 68, 71, 72, 130, 248, 323, 109, 110,
	111, 112, 113, 74, 327, 268, 269, 270, 271, 272,
	273, 274, 275, 276, 277, 278, 279, 114, 140, 141,
	142, 104, 143, 90, 87, 494, 481, 390, 389, 58,
	59, 89, 495, 482, 496, 33, 57, 388, 324, 387,
	386, 385, 369, 368, 210, 325, 211, 212, 34, 35,
	215, 340, 213, 249, 478, 246, 312, 242, 319, 241,
	240, 233, 350, 222, 86, 82, 319, 81, 80, 354,
	343, 345, 347, 79, 25, 214, 24, 23, 323, 352,
	22, 101, 356, 358, 361, 363, 34, 35, 366, 39,
	40, 45, 46, 47, 48, 49, 50, 41, 42, 43,
	44, 51, 52, 34, 35, 135, 34, 35, 133, 34,
	35, 129, 34, 35, 118, 97, 341, 34, 35, 381,
	34, 35, 383, 102, 236, 124, 235, 125, 54, 91,
	477, 461, 338, 353, 349, 407, 348, 310, 296, 295,
	292, 257, 440, 254, 253, 252, 251, 250, 447, 234,
	230, 226, 225, 224, 223, 123, 456, 122, 107, 100,
	462, 99, 464, 84, 36, 28, 27, 26, 470, 469,
	472, 497, 484, 483, 476, 475, 474, 473, 471, 480,
	467, 466, 465, 463, 460, 459, 458, 453, 452, 451,
	450, 449, 445, 444, 443, 442, 441, 384, 491, 146,
	147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
	157, 158, 159, 160, 161, 162, 163, 370, 364, 164,
	165, 166, 339, 307, 306, 305, 304, 301, 300, 493,
	299, 294, 491, 499, 293, 286, 266, 262, 261, 260,
	259, 258, 245, 167, 168, 169, 170, 171, 172, 173,
	174, 239, 238, 237, 229, 126, 103, 98, 95, 94,
	93, 92, 85, 83, 1, 208, 322, 21, 314, 434,
	423, 409, 486, 400, 393, 372, 287, 29, 203, 176,
	337, 333, 329, 326, 145, 309, 137, 76, 38, 11,
	10, 9, 8, 7, 6, 5, 4, 3, 2,
}
var yyPact = [...]int{

	127, -1000, 127, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 326, 323, 322, 320, 421, 420, 419, 68,
	418, -1000, 332, 224, 174, 42, 319, 314, 313, 311,
	-1000, 519, 417, 518, -1000, -1000, 310, 269, 332, 277,
	382, 517, 516, 515, 514, 369, 513, 415, 413, 333,
	374, 512, -1000, 266, 224, -1000, -1000, 338, 412, 191,
	262, 174, 338, 364, -1000, -1000, 338, 338, 338, 411,
	409, 381, 511, 191, 361, 240, 42, 358, 355, 194,
	422, 95, 22, -1000, -1000, -1000, 48, -1000, -1000, 300,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 4, 1, 0, -19, 231, 194, -1000, 309,
	408, 407, 406, 405, 221, 422, -1000, 510, -1000, -1000,
	404, 338, 338, 307, 403, 380, -1000, 509, 508, 507,
	306, 305, 303, 97, 498, -1000, 301, 242, 299, -1000,
	401, 400, 399, 398, 397, 220, 95, 395, 497, 496,
	495, 494, 493, 215, 22, 174, 492, 161, -43, 161,
	-43, 491, -82, 338, 338, 394, -1000, -1000, 490, 487,
	393, 392, 212, 48, 486, 484, 483, 211, 300, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 482, 481, 480, 479,
	-1000, -1000, 391, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 338, -1000, -1000, -1000, -1000, -1000, -1000,
	130, 233, 22, -1000, -1000, -1000, 59, -1000, 63, 386,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	478, 372, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 208, 391,
	-1000, 207, 338, 206, 130, -1000, 390, 388, 338, -1000,
	-1000, 204, 233, -1000, 387, 338, 199, 22, 198, 59,
	50, 300, 193, 63, -1000, 474, 190, 386, -41, -1000,
	289, 288, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 473, 38, 38,
	-1000, 189, 38, 453, -1000, 287, 286, 285, 283, 274,
	273, 186, -1000, -1000, -1000, -96, -100, -100, -33, -11,
	-84, -1000, 181, -96, 452, 451, 450, 449, 448, 177,
	-100, 195, 447, 446, 445, 444, 443, 156, 139, -33,
	-1000, 192, 442, 441, 440, 385, 338, 439, 338, 438,
	437, 436, 122, -11, 338, 434, 338, 433, 432, 431,
	430, 384, 308, 79, -84, 280, 429, 428, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -91, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 10, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 69, -91, 279, 282, 427,
	53, 10, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
}
var yyPgo = [...]int{

	0, 524, 558, 557, 556, 555, 554, 553, 552, 551,
	550, 549, 172, 548, 22, 3, 89, 34, 85, 547,
	47, 546, 20, 545, 35, 544, 18, 17, 16, 543,
	13, 11, 10, 542, 12, 541, 540, 26, 539, 21,
	14, 29, 24, 538, 537, 19, 28, 25, 536, 9,
	535, 8, 7, 6, 5, 4, 534, 533, 2, 532,
	531, 0, 1, 530, 529, 528, 526, 15, 525, 388,
	136,
}
var yyR1 = [...]int{

	0, 1, 1, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 3, 12, 12, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 4, 5, 6, 18, 18, 7, 20,
	20, 21, 21, 21, 21, 21, 21, 21, 22, 22,
	23, 8, 24, 24, 25, 25, 25, 25, 25, 25,
	25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
	25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
	25, 25, 25, 25, 25, 25, 25, 30, 30, 33,
	33, 33, 33, 31, 31, 35, 35, 26, 26, 32,
	32, 36, 36, 36, 9, 37, 37, 38, 38, 38,
	38, 38, 38, 38, 29, 29, 39, 39, 11, 42,
	42, 43, 43, 43, 43, 10, 40, 40, 44, 44,
	44, 44, 39, 39, 39, 39, 39, 39, 39, 39,
	39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
	49, 49, 50, 50, 50, 50, 50, 50, 50, 50,
	50, 51, 51, 56, 56, 56, 56, 56, 56, 52,
	52, 57, 57, 57, 57, 57, 57, 57, 58, 58,
	59, 59, 59, 59, 59, 53, 53, 60, 60, 60,
	60, 60, 60, 60, 62, 62, 61, 61, 61, 61,
	61, 61, 61, 54, 54, 63, 63, 63, 63, 63,
	63, 63, 63, 63, 63, 55, 55, 64, 64, 64,
	64, 64, 64, 46, 46, 46, 46, 46, 46, 46,
	46, 46, 46, 46, 46, 46, 47, 47, 47, 47,
	48, 48, 48, 27, 27, 28, 28, 65, 65, 65,
	65, 66, 66, 66, 14, 14, 68, 16, 16, 69,
	69, 69, 69, 69, 69, 17, 17, 41, 41, 41,
	41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
	41, 41, 41, 41, 19, 19, 19, 19, 19, 70,
	70, 70, 70, 70, 70, 67, 67, 67, 15, 15,
	15, 45, 45, 45, 34, 34, 34, 34, 34, 34,
	34,
}
var yyR2 = [...]int{

	0, 2, 1, 0, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 4, 2, 1, 0, 4, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 1, 4, 4, 4, 2, 1, 5, 2,
	1, 0, 1, 4, 2, 2, 2, 2, 2, 1,
	1, 5, 2, 1, 0, 1, 2, 1, 1, 2,
	2, 2, 4, 2, 2, 2, 1, 2, 2, 2,
	4, 4, 4, 2, 2, 2, 1, 4, 2, 4,
	4, 1, 2, 2, 2, 2, 2, 2, 1, 0,
	2, 2, 2, 2, 1, 1, 2, 2, 1, 2,
	1, 0, 1, 3, 5, 2, 1, 0, 2, 2,
	2, 2, 2, 2, 2, 1, 2, 1, 5, 2,
	1, 0, 2, 2, 2, 5, 2, 1, 0, 1,
	2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
	3, 6, 6, 2, 1, 1, 2, 2, 2, 2,
	2, 1, 0, 2, 1, 4, 4, 4, 4, 4,
	4, 2, 1, 0, 2, 2, 2, 2, 2, 2,
	1, 0, 4, 2, 2, 2, 2, 2, 2, 1,
	0, 2, 2, 2, 2, 2, 1, 0, 1, 4,
	2, 2, 2, 2, 2, 1, 0, 2, 2, 2,
	2, 2, 2, 2, 1, 0, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 1, 0, 2, 2,
	2, 2, 1, 0, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
	0, 1, 1, 2, 1, 2, 1, 1, 2, 2,
	2, 1, 2, 2, 2, 1, 1, 2, 1, 0,
	1, 1, 2, 2, 2, 2, 1, 0, 2, 2,
	2, 1, 1, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 0, 4, 4, 4, 4, 0,
	1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
	1, 0, 1, 2, 0, 1, 1, 1, 1, 1,
	1,
}
var yyChk = [...]int{

	-1000, -1, -2, -3, -4, -5, -6, -7, -8, -9,
	-10, -11, 16, 31, 32, 33, 34, 36, 90, 98,
	97, -1, 14, 14, 14, 14, 6, 6, 6, -44,
	-45, 125, 35, -15, 8, 9, 6, -12, -13, 17,
	18, 25, 26, 27, 28, 19, 20, 21, 22, 23,
	24, 29, 30, -16, -69, -15, 10, 72, 65, 66,
	-17, -41, 73, 75, -15, 10, 76, 77, 78, 65,
	64, 79, 80, 66, 89, -18, -19, 74, 75, 14,
	14, 14, 14, 4, 6, 4, 14, 15, -12, 14,
	6, 7, 4, 4, 4, 4, -15, 6, 4, 6,
	6, 8, 9, 4, 15, -16, -15, 6, -70, 67,
	68, 69, 70, 71, 15, -17, -15, -15, 10, -15,
	-15, -15, 6, 6, 4, 6, 4, -70, -15, 10,
	15, -18, -15, 10, -15, 10, -20, -21, 6, 35,
	84, 85, 86, 88, -24, -25, 37, 38, 39, 40,
	41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
	51, 52, 53, 54, 57, 58, 59, 81, 82, 83,
	84, 85, 86, 87, 88, -37, -38, 91, 92, 93,
	94, 95, 96, -40, -39, -41, 99, 100, 101, 102,
	103, 119, 120, 123, 124, 152, 153, 154, 155, 156,
	157, 158, -42, -43, -15, 11, 125, -14, -68, -34,
	4, 6, 7, 12, -15, 10, 79, 79, 79, 79,
	15, -20, 14, 6, 6, 6, 6, 15, -24, 4,
	6, -15, -15, 14, 6, 6, 4, 4, 4, 4,
	14, 14, 14, 55, 56, 4, 14, 6, 14, 14,
	6, 6, 6, 6, 6, 15, -37, 6, 4, 4,
	4, 4, 4, 15, -40, -17, 4, -46, 104, 105,
	106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
	-47, 116, 117, 118, -46, -47, 4, -48, 121, 122,
	-15, -15, 6, 4, 4, 6, 6, 15, -42, 4,
	4, 4, 15, -14, 4, 4, 4, 4, -22, -23,
	6, -26, -15, -27, -65, -67, 64, 65, 72, -15,
	10, -28, -66, -67, 65, 72, -29, -39, -30, -33,
	60, 61, -31, -35, 6, 94, -32, -36, 6, 4,
	-45, 4, 15, -22, 15, -26, 15, -27, 6, 6,
	-15, 15, -28, 6, -15, 15, -40, 15, -30, 62,
	63, -34, 15, -31, 4, 15, -32, 94, 14, 14,
	4, -49, -50, 94, 126, 127, 128, 129, 130, 131,
	132, -49, 15, -49, 4, 14, 14, 14, 14, 14,
	14, 15, -51, -56, 138, 137, 142, 148, 151, -52,
	-57, 133, 137, 138, 150, 151, 148, -52, -53, -60,
	-61, 69, 148, 142, 151, 143, 139, 138, 140, 141,
	137, 125, -54, -63, 139, 138, 140, 141, 137, 125,
	142, 144, 145, -55, -64, 146, 147, 148, 149, 15,
	-51, 4, 4, 4, 4, 4, 15, -52, 14, 4,
	4, 4, 4, 4, 15, 15, -53, 14, 4, 4,
	4, 6, -15, 4, -15, 4, 4, 4, 15, -54,
	-15, 4, -15, 4, 4, 4, 4, 6, 6, 15,
	-55, 6, 13, 4, 4, -58, -59, 134, 135, 136,
	-62, -61, 15, -58, 6, 13, 12, 4, 15, -62,
}
var yyDef = [...]int{

	3, -2, 2, 4, 5, 6, 7, 8, 9, 10,
	11, 12, 0, 0, 0, 0, 0, 0, 0, -2,
	0, 1, 16, 259, 267, 284, 0, 0, 0, 0,
	129, 0, 0, 302, 299, 300, 0, 0, 15, 0,
	0, 0, 0, 0, 0, 298, 0, 0, 0, 0,
	0, 0, 32, 0, 258, 260, 261, 298, 0, 289,
	0, 266, 298, 298, 271, 272, 298, 298, 298, 0,
	0, 0, 0, 289, 298, 0, 37, 298, 298, 41,
	54, 107, 132, 130, 131, 303, 121, 13, 14, 298,
	18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
	28, 29, 30, 31, 33, 257, 262, 263, 264, 290,
	291, 292, 293, 294, 34, 265, 268, 269, 270, 273,
	274, 275, 276, 277, 278, 279, 280, 281, 282, 283,
	35, 36, 0, 0, 0, 0, 0, 40, 42, 0,
	0, 0, 0, 0, 0, 53, 55, 0, 57, 58,
	0, 298, 298, 0, 0, 0, 66, 0, 0, 0,
	0, 0, 0, 0, 0, 76, 0, 0, 0, 81,
	0, 0, 0, 0, 0, 0, 106, 0, 0, 0,
	0, 0, 0, 0, 127, 117, 0, 223, 236, 223,
	236, 0, 240, 298, 298, 0, 144, 145, 0, 0,
	0, 0, 0, -2, 0, 0, 0, 0, 255, 256,
	305, 306, 307, 308, 309, 310, 0, 0, 0, 0,
	38, 39, 0, 44, 45, 46, 47, 51, 52, 56,
	59, 60, 61, 298, 63, 64, 65, 67, 68, 69,
	295, 295, 132, 73, 74, 75, 89, 78, 0, 101,
	82, 83, 84, 85, 86, 104, 105, 108, 109, 110,
	111, 112, 113, 125, 126, 116, 133, 134, 224, 225,
	226, 227, 228, 229, 230, 231, 232, 233, 234, 235,
	135, 237, 238, 239, 136, 137, 138, 139, 241, 242,
	0, 298, 143, 146, 147, 148, 149, 118, 119, 122,
	123, 124, 17, 254, 285, 287, 286, 288, 0, 49,
	50, 0, 98, 0, 244, 247, 0, 0, 298, 296,
	297, 0, 246, 251, 0, 298, 0, 115, 0, 88,
	0, 298, 0, 94, 95, 0, 0, 100, 102, 140,
	0, 0, 43, 48, 62, 97, 70, 243, 248, 249,
	250, 71, 245, 252, 253, 72, 114, 77, 87, 90,
	91, 92, 79, 93, 96, 80, 99, 0, 152, 152,
	103, 0, 151, 0, 154, 0, 0, 0, 0, 0,
	0, 0, 141, 150, 153, 163, 171, 171, 187, 205,
	217, 142, 0, 162, 0, 0, 0, 0, 0, 0,
	170, 0, 0, 0, 0, 0, 0, 0, 0, 186,
	188, 0, 0, 0, 0, 0, 298, 0, 298, 0,
	0, 0, 0, 204, 298, 0, 298, 0, 0, 0,
	0, 0, 0, 0, 216, 0, 0, 0, 222, 155,
	161, 164, 165, 166, 167, 168, 156, 169, 180, 173,
	174, 175, 176, 177, 157, 158, 185, 196, 190, 191,
	192, 193, 197, 198, 199, 200, 201, 202, 159, 203,
	206, 207, 208, 209, 210, 211, 212, 213, 214, 160,
	215, 218, 219, 220, 221, 0, 179, 0, 0, 0,
	0, 195, 172, 178, 181, 182, 183, 184, 189, 194,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
	122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
	132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
	142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
	152, 153, 154, 155, 156, 157, 158,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:29
		{
		}
	case 3:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:31
		{
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:32
		{
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:33
		{
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:34
		{
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:35
		{
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:36
		{
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:37
		{
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:38
		{
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:39
		{
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:40
		{
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:47
		{
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:48
		{
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:49
		{
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:50
		{
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:51
		{
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:52
		{
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:53
		{
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:54
		{
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:55
		{
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:56
		{
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:57
		{
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:58
		{
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:59
		{
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:60
		{
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:61
		{
		}
	case 41:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:76
		{
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:77
		{
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:78
		{
		}
	case 44:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:79
		{
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:80
		{
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:81
		{
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:82
		{
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:84
		{
		}
	case 54:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:92
		{
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:93
		{
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:94
		{
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:95
		{
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:96
		{
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:97
		{
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:98
		{
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:99
		{
		}
	case 62:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:100
		{
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:101
		{
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:102
		{
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:103
		{
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:105
		{
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:106
		{
		}
	case 69:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:107
		{
		}
	case 73:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:111
		{
		}
	case 74:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:112
		{
		}
	case 75:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:113
		{
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:114
		{
		}
	case 77:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:115
		{
		}
	case 78:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:116
		{
		}
	case 79:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:117
		{
		}
	case 80:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:118
		{
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:119
		{
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:120
		{
		}
	case 83:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:121
		{
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:122
		{
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:123
		{
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:124
		{
		}
	case 89:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:128
		{
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:129
		{
		}
	case 91:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:130
		{
		}
	case 92:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:131
		{
		}
	case 96:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:136
		{
		}
	case 101:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:142
		{
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:143
		{
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.go.y:144
		{
		}
	case 107:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:150
		{
		}
	case 108:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:151
		{
		}
	case 109:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:152
		{
		}
	case 110:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:153
		{
		}
	case 111:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:154
		{
		}
	case 112:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:155
		{
		}
	case 113:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:156
		{
		}
	case 121:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:166
		{
		}
	case 122:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:167
		{
		}
	case 123:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:168
		{
		}
	case 124:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:169
		{
		}
	case 130:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:177
		{
		}
	case 131:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:178
		{
		}
	case 132:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:180
		{
		}
	case 133:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:181
		{
		}
	case 134:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:182
		{
		}
	case 135:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:183
		{
		}
	case 136:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:184
		{
		}
	case 137:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:185
		{
		}
	case 138:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:186
		{
		}
	case 139:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:187
		{
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.go.y:188
		{
		}
	case 143:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:191
		{
		}
	case 146:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:194
		{
		}
	case 147:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:195
		{
		}
	case 148:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:196
		{
		}
	case 149:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:197
		{
		}
	case 151:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:199
		{
		}
	case 152:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:201
		{
		}
	case 153:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:202
		{
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:203
		{
		}
	case 155:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:204
		{
		}
	case 156:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:205
		{
		}
	case 157:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:206
		{
		}
	case 158:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:207
		{
		}
	case 159:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:208
		{
		}
	case 160:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:209
		{
		}
	case 162:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:211
		{
		}
	case 163:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:213
		{
		}
	case 164:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:214
		{
		}
	case 165:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:215
		{
		}
	case 166:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:216
		{
		}
	case 167:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:217
		{
		}
	case 168:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:218
		{
		}
	case 170:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:220
		{
		}
	case 171:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:222
		{
		}
	case 172:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:223
		{
		}
	case 173:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:224
		{
		}
	case 174:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:225
		{
		}
	case 175:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:226
		{
		}
	case 176:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:227
		{
		}
	case 177:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:228
		{
		}
	case 179:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:230
		{
		}
	case 180:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:232
		{
		}
	case 181:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:233
		{
		}
	case 182:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:234
		{
		}
	case 183:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:235
		{
		}
	case 184:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:236
		{
		}
	case 186:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:238
		{
		}
	case 187:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:240
		{
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:241
		{
		}
	case 195:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:248
		{
		}
	case 196:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:250
		{
		}
	case 197:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:251
		{
		}
	case 198:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:252
		{
		}
	case 199:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:253
		{
		}
	case 200:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:254
		{
		}
	case 201:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:255
		{
		}
	case 202:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:256
		{
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:258
		{
		}
	case 205:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:260
		{
		}
	case 206:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:261
		{
		}
	case 207:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:262
		{
		}
	case 208:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:263
		{
		}
	case 209:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:264
		{
		}
	case 210:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:265
		{
		}
	case 211:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:266
		{
		}
	case 212:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:267
		{
		}
	case 213:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:268
		{
		}
	case 214:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:269
		{
		}
	case 216:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:271
		{
		}
	case 217:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:273
		{
		}
	case 218:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:274
		{
		}
	case 219:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:275
		{
		}
	case 220:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:276
		{
		}
	case 221:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:277
		{
		}
	case 222:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:278
		{
		}
	case 223:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:280
		{
		}
	case 224:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:281
		{
		}
	case 225:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:282
		{
		}
	case 226:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:283
		{
		}
	case 227:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:284
		{
		}
	case 228:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:285
		{
		}
	case 229:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:286
		{
		}
	case 230:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:287
		{
		}
	case 231:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:288
		{
		}
	case 232:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:289
		{
		}
	case 233:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:290
		{
		}
	case 234:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:291
		{
		}
	case 235:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:292
		{
		}
	case 236:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:294
		{
		}
	case 237:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:295
		{
		}
	case 238:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:296
		{
		}
	case 239:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:297
		{
		}
	case 240:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:299
		{
		}
	case 241:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:300
		{
		}
	case 242:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:301
		{
		}
	case 244:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:303
		{
		}
	case 246:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:305
		{
		}
	case 247:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:307
		{
		}
	case 248:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:308
		{
		}
	case 249:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:309
		{
		}
	case 250:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:310
		{
		}
	case 251:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:312
		{
		}
	case 252:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:313
		{
		}
	case 253:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:314
		{
		}
	case 255:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:316
		{
		}
	case 256:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:318
		{
		}
	case 259:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:322
		{
		}
	case 267:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:331
		{
		}
	case 284:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:349
		{
		}
	case 289:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:355
		{
		}
	case 295:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:362
		{
		}
	case 298:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:366
		{
		}
	case 301:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:370
		{
		}
	case 304:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:374
		{
		}
	}
	goto yystack /* stack new state and value */
}
