// Code generated by goyacc -o parser/parser.go -v parser/parser.output parser/parser.go.y. DO NOT EDIT.

//line parser/parser.go.y:2
package parser

import __yyfmt__ "fmt"

//line parser/parser.go.y:2

//line parser/parser.go.y:5
type yySymType struct {
	yys     int
	integer int
	symbol  string
}

const NUMBER = 57346
const ID = 57347
const STRING = 57348
const EMAIL = 57349
const IPV4 = 57350
const IPV6 = 57351
const IP_CIDR = 57352
const IPADDR_RANGE = 57353
const HEX32 = 57354
const PATHSTR = 57355
const LB = 57356
const RB = 57357
const GLOBALDEFS = 57358
const NOTIFICATION_EMAIL = 57359
const NOTIFICATION_EMAIL_FROM = 57360
const SMTP_SERVER = 57361
const SMTP_CONNECT_TIMEOUT = 57362
const ROUTER_ID = 57363
const LVS_ID = 57364
const VRRP_MCAST_GROUP4 = 57365
const VRRP_MCAST_GROUP6 = 57366
const VRRP_GARP_MASTER_DELAY = 57367
const VRRP_GARP_MASTER_REPEAT = 57368
const VRRP_GARP_MASTER_REFRESH = 57369
const VRRP_GARP_MASTER_REFRESH_REPEAT = 57370
const VRRP_VERSION = 57371
const ENABLE_SCRIPT_SECURITY = 57372
const STATIC_IPADDRESS = 57373
const STATIC_ROUTES = 57374
const STATIC_RULES = 57375
const VRRP_SYNC_GROUP = 57376
const GROUP = 57377
const VRRP_INSTANCE = 57378
const USE_VMAC = 57379
const VERSION = 57380
const VMAC_XMIT_BASE = 57381
const NATIVE_IPV6 = 57382
const INTERFACE = 57383
const MCAST_SRC_IP = 57384
const UNICAST_SRC_IP = 57385
const UNICAST_PEER = 57386
const LVS_SYNC_DAEMON_INTERFACE = 57387
const VIRTUAL_ROUTER_ID = 57388
const NOPREEMPT = 57389
const PREEMPT_DELAY = 57390
const PRIORITY = 57391
const ADVERT_INT = 57392
const VIRTUAL_IPADDRESS = 57393
const VIRTUAL_IPADDRESS_EXCLUDED = 57394
const VIRTUAL_ROUTES = 57395
const STATE = 57396
const MASTER = 57397
const BACKUP = 57398
const GARP_MASTER_DELAY = 57399
const GARP_MASTER_REPEAT = 57400
const GARP_MASTER_REFRESH = 57401
const GARP_MASTER_REFRESH_REPEAT = 57402
const SMTP_ALERT = 57403
const AUTHENTICATION = 57404
const AUTH_TYPE = 57405
const AUTH_PASS = 57406
const PASS = 57407
const AH = 57408
const LABEL = 57409
const DEV = 57410
const SCOPE = 57411
const SITE = 57412
const LINK = 57413
const HOST = 57414
const NOWHERE = 57415
const GLOBAL = 57416
const BRD = 57417
const SRC = 57418
const FROM = 57419
const TO = 57420
const VIA = 57421
const GW = 57422
const OR = 57423
const TABLE = 57424
const METRIC = 57425
const TRACK_INTERFACE = 57426
const TRACK_SCRIPT = 57427
const DONT_TRACK_PRIMARY = 57428
const NOTIFY_MASTER = 57429
const NOTIFY_BACKUP = 57430
const NOTIFY_FAULT = 57431
const NOTIFY_STOP = 57432
const NOTIFY = 57433
const BLACKHOLE = 57434
const VRRP_SCRIPT = 57435
const SCRIPT = 57436
const INTERVAL = 57437
const TIMEOUT = 57438
const WEIGHT = 57439
const FALL = 57440
const RISE = 57441
const VIRTUAL_SERVER_GROUP = 57442
const VIRTUAL_SERVER = 57443
const DELAY_LOOP = 57444
const LB_ALGO = 57445
const LB_KIND = 57446
const LVS_SCHED = 57447
const LVS_METHOD = 57448
const RR = 57449
const WRR = 57450
const LC = 57451
const WLC = 57452
const FO = 57453
const OVF = 57454
const LBLC = 57455
const LBLCR = 57456
const SH = 57457
const DH = 57458
const SED = 57459
const NQ = 57460
const NAT = 57461
const DR = 57462
const TUN = 57463
const PERSISTENCE_TIMEOUT = 57464
const PROTOCOL = 57465
const TCP = 57466
const UDP = 57467
const SORRY_SERVER = 57468
const REAL_SERVER = 57469
const FWMARK = 57470
const INHIBIT_ON_FAILURE = 57471
const TCP_CHECK = 57472
const HTTP_GET = 57473
const SSL_GET = 57474
const SMTP_CHECK = 57475
const DNS_CHECK = 57476
const MISC_CHECK = 57477
const URL = 57478
const PATH = 57479
const DIGEST = 57480
const STATUS_CODE = 57481
const CONNECT_TIMEOUT = 57482
const CONNECT_PORT = 57483
const CONNECT_IP = 57484
const BINDTO = 57485
const BIND_PORT = 57486
const RETRY = 57487
const HELO_NAME = 57488
const TYPE = 57489
const NAME = 57490
const MISC_PATH = 57491
const MISC_TIMEOUT = 57492
const WARMUP = 57493
const MISC_DYNAMIC = 57494
const NB_GET_RETRY = 57495
const DELAY_BEFORE_RETRY = 57496
const VIRTUALHOST = 57497
const ALPHA = 57498
const OMEGA = 57499
const QUORUM = 57500
const HYSTERESIS = 57501
const QUORUM_UP = 57502
const QUORUM_DOWN = 57503

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUMBER",
	"ID",
	"STRING",
	"EMAIL",
	"IPV4",
	"IPV6",
	"IP_CIDR",
	"IPADDR_RANGE",
	"HEX32",
	"PATHSTR",
	"LB",
	"RB",
	"GLOBALDEFS",
	"NOTIFICATION_EMAIL",
	"NOTIFICATION_EMAIL_FROM",
	"SMTP_SERVER",
	"SMTP_CONNECT_TIMEOUT",
	"ROUTER_ID",
	"LVS_ID",
	"VRRP_MCAST_GROUP4",
	"VRRP_MCAST_GROUP6",
	"VRRP_GARP_MASTER_DELAY",
	"VRRP_GARP_MASTER_REPEAT",
	"VRRP_GARP_MASTER_REFRESH",
	"VRRP_GARP_MASTER_REFRESH_REPEAT",
	"VRRP_VERSION",
	"ENABLE_SCRIPT_SECURITY",
	"STATIC_IPADDRESS",
	"STATIC_ROUTES",
	"STATIC_RULES",
	"VRRP_SYNC_GROUP",
	"GROUP",
	"VRRP_INSTANCE",
	"USE_VMAC",
	"VERSION",
	"VMAC_XMIT_BASE",
	"NATIVE_IPV6",
	"INTERFACE",
	"MCAST_SRC_IP",
	"UNICAST_SRC_IP",
	"UNICAST_PEER",
	"LVS_SYNC_DAEMON_INTERFACE",
	"VIRTUAL_ROUTER_ID",
	"NOPREEMPT",
	"PREEMPT_DELAY",
	"PRIORITY",
	"ADVERT_INT",
	"VIRTUAL_IPADDRESS",
	"VIRTUAL_IPADDRESS_EXCLUDED",
	"VIRTUAL_ROUTES",
	"STATE",
	"MASTER",
	"BACKUP",
	"GARP_MASTER_DELAY",
	"GARP_MASTER_REPEAT",
	"GARP_MASTER_REFRESH",
	"GARP_MASTER_REFRESH_REPEAT",
	"SMTP_ALERT",
	"AUTHENTICATION",
	"AUTH_TYPE",
	"AUTH_PASS",
	"PASS",
	"AH",
	"LABEL",
	"DEV",
	"SCOPE",
	"SITE",
	"LINK",
	"HOST",
	"NOWHERE",
	"GLOBAL",
	"BRD",
	"SRC",
	"FROM",
	"TO",
	"VIA",
	"GW",
	"OR",
	"TABLE",
	"METRIC",
	"TRACK_INTERFACE",
	"TRACK_SCRIPT",
	"DONT_TRACK_PRIMARY",
	"NOTIFY_MASTER",
	"NOTIFY_BACKUP",
	"NOTIFY_FAULT",
	"NOTIFY_STOP",
	"NOTIFY",
	"BLACKHOLE",
	"VRRP_SCRIPT",
	"SCRIPT",
	"INTERVAL",
	"TIMEOUT",
	"WEIGHT",
	"FALL",
	"RISE",
	"VIRTUAL_SERVER_GROUP",
	"VIRTUAL_SERVER",
	"DELAY_LOOP",
	"LB_ALGO",
	"LB_KIND",
	"LVS_SCHED",
	"LVS_METHOD",
	"RR",
	"WRR",
	"LC",
	"WLC",
	"FO",
	"OVF",
	"LBLC",
	"LBLCR",
	"SH",
	"DH",
	"SED",
	"NQ",
	"NAT",
	"DR",
	"TUN",
	"PERSISTENCE_TIMEOUT",
	"PROTOCOL",
	"TCP",
	"UDP",
	"SORRY_SERVER",
	"REAL_SERVER",
	"FWMARK",
	"INHIBIT_ON_FAILURE",
	"TCP_CHECK",
	"HTTP_GET",
	"SSL_GET",
	"SMTP_CHECK",
	"DNS_CHECK",
	"MISC_CHECK",
	"URL",
	"PATH",
	"DIGEST",
	"STATUS_CODE",
	"CONNECT_TIMEOUT",
	"CONNECT_PORT",
	"CONNECT_IP",
	"BINDTO",
	"BIND_PORT",
	"RETRY",
	"HELO_NAME",
	"TYPE",
	"NAME",
	"MISC_PATH",
	"MISC_TIMEOUT",
	"WARMUP",
	"MISC_DYNAMIC",
	"NB_GET_RETRY",
	"DELAY_BEFORE_RETRY",
	"VIRTUALHOST",
	"ALPHA",
	"OMEGA",
	"QUORUM",
	"HYSTERESIS",
	"QUORUM_UP",
	"QUORUM_DOWN",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/parser.go.y:385

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 19,
	14, 131,
	-2, 301,
	-1, 206,
	15, 123,
	-2, 124,
}

const yyPrivate = 57344

const yyLast = 565

var yyAct = [...]int{

	416, 496, 491, 64, 439, 428, 414, 405, 398, 377,
	342, 338, 212, 334, 186, 321, 327, 319, 317, 30,
	314, 187, 210, 33, 205, 286, 178, 55, 273, 188,
	441, 442, 443, 444, 144, 34, 35, 65, 60, 401,
	400, 136, 407, 417, 402, 373, 408, 409, 222, 96,
	403, 294, 295, 404, 61, 221, 340, 412, 55, 410,
	411, 106, 493, 494, 495, 220, 116, 117, 219, 504,
	119, 120, 121, 427, 34, 35, 498, 208, 128, 77,
	78, 132, 134, 108, 485, 426, 423, 422, 424, 425,
	207, 61, 474, 217, 70, 69, 73, 34, 35, 427,
	115, 75, 37, 62, 463, 63, 66, 67, 68, 71,
	72, 426, 423, 422, 424, 425, 419, 421, 461, 74,
	365, 366, 418, 435, 32, 420, 379, 336, 337, 189,
	190, 191, 192, 193, 53, 434, 431, 430, 432, 433,
	436, 88, 437, 438, 287, 288, 289, 341, 460, 194,
	195, 246, 247, 196, 197, 234, 235, 127, 380, 381,
	382, 383, 384, 385, 386, 274, 275, 276, 277, 278,
	279, 280, 281, 282, 283, 284, 285, 452, 131, 224,
	231, 445, 198, 199, 200, 201, 202, 203, 204, 105,
	397, 34, 35, 65, 209, 454, 12, 388, 502, 371,
	296, 297, 270, 138, 368, 363, 262, 361, 357, 352,
	207, 13, 14, 15, 16, 217, 17, 31, 61, 291,
	350, 290, 348, 34, 35, 326, 308, 271, 303, 269,
	253, 304, 139, 261, 309, 34, 35, 56, 254, 396,
	318, 180, 181, 182, 183, 184, 185, 325, 325, 230,
	70, 69, 73, 34, 35, 326, 223, 130, 114, 62,
	329, 63, 66, 67, 68, 71, 72, 333, 109, 110,
	111, 112, 113, 18, 104, 74, 87, 395, 394, 90,
	20, 19, 322, 323, 140, 141, 142, 89, 143, 393,
	324, 500, 487, 392, 391, 58, 59, 375, 501, 488,
	102, 33, 57, 213, 374, 214, 215, 34, 35, 218,
	255, 216, 252, 330, 245, 244, 243, 346, 236, 225,
	331, 86, 318, 82, 325, 81, 80, 79, 356, 25,
	24, 23, 325, 22, 101, 360, 349, 351, 353, 91,
	97, 217, 34, 35, 329, 358, 484, 483, 362, 364,
	367, 369, 34, 35, 372, 39, 40, 45, 46, 47,
	48, 49, 50, 41, 42, 43, 44, 51, 52, 34,
	35, 135, 34, 35, 133, 34, 35, 129, 34, 35,
	118, 239, 347, 238, 503, 387, 34, 35, 389, 124,
	467, 125, 344, 359, 355, 354, 316, 302, 301, 298,
	263, 413, 260, 259, 258, 257, 256, 237, 446, 233,
	229, 228, 227, 226, 453, 123, 122, 107, 100, 99,
	84, 36, 462, 28, 27, 26, 468, 490, 470, 489,
	482, 481, 54, 480, 476, 475, 478, 479, 477, 473,
	472, 471, 469, 466, 465, 486, 464, 459, 458, 457,
	456, 455, 451, 450, 449, 448, 447, 390, 376, 370,
	345, 313, 312, 311, 497, 146, 147, 148, 149, 150,
	151, 152, 153, 154, 155, 156, 157, 158, 159, 160,
	161, 162, 163, 310, 307, 164, 165, 166, 167, 168,
	169, 306, 305, 300, 299, 499, 292, 272, 497, 505,
	268, 267, 266, 265, 264, 251, 250, 249, 248, 242,
	241, 240, 170, 171, 172, 173, 174, 175, 176, 177,
	232, 126, 103, 98, 95, 94, 93, 92, 85, 83,
	1, 211, 328, 21, 320, 440, 429, 415, 492, 406,
	399, 378, 293, 29, 206, 179, 343, 339, 335, 332,
	145, 315, 137, 76, 38, 11, 10, 9, 8, 7,
	6, 5, 4, 3, 2,
}
var yyPact = [...]int{

	180, -1000, 180, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 319, 317, 316, 315, 419, 418, 417, 89,
	415, -1000, 338, 227, 183, 2, 313, 312, 311, 309,
	-1000, 525, 414, 524, -1000, -1000, 307, 261, 338, 273,
	332, 523, 522, 521, 520, 334, 519, 413, 412, 326,
	291, 518, -1000, 259, 227, -1000, -1000, 344, 411, 198,
	243, 183, 344, 370, -1000, -1000, 344, 344, 344, 410,
	409, 385, 517, 198, 367, 242, 2, 364, 361, 197,
	428, 147, 27, -1000, -1000, -1000, 66, -1000, -1000, 299,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -14, -17, -27, -34, 241, 197, -1000, 305,
	407, 406, 405, 404, 234, 428, -1000, 516, -1000, -1000,
	403, 344, 344, 304, 401, 377, -1000, 507, 506, 505,
	302, 301, 300, 96, 504, 503, 502, 501, -1000, 298,
	224, 296, -1000, 400, 399, 398, 397, 396, 218, 147,
	394, 500, 499, 498, 497, 496, 214, 27, 183, 493,
	58, 25, 58, 25, 492, -73, 344, 344, 393, -1000,
	-1000, 490, 489, 392, 391, 213, 66, 488, 487, 480,
	211, 299, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 479,
	459, 458, 457, -1000, -1000, 390, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 344, -1000, -1000, -1000,
	-1000, -1000, -1000, 215, 245, 27, -1000, -1000, -1000, -1000,
	-1000, -1000, 64, -1000, 50, 386, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 456, 378, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 207, 390, -1000, 205, 344, 194,
	215, -1000, 389, 388, 344, -1000, -1000, 193, 245, -1000,
	387, 344, 192, 27, 190, 64, 55, 299, 189, 50,
	-1000, 455, 184, 386, -52, -1000, 290, 283, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 454, 29, 29, -1000, 182, 29, 453,
	-1000, 280, 279, 275, 264, 263, 225, 175, -1000, -1000,
	-1000, -101, -94, -94, -29, -5, -119, -1000, 166, -101,
	452, 451, 450, 449, 448, 162, -94, 181, 447, 446,
	445, 444, 443, 133, 103, -29, -1000, 90, 442, 440,
	439, 384, 344, 438, 344, 437, 436, 435, 77, -5,
	344, 434, 344, 433, 429, 427, 426, 341, 340, 69,
	-119, 286, 425, 423, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -75, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -55, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 61, -75, 285, 186, 380, 54, -55, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000,
}
var yyPgo = [...]int{

	0, 530, 564, 563, 562, 561, 560, 559, 558, 557,
	556, 555, 102, 554, 22, 3, 134, 38, 101, 553,
	41, 552, 20, 551, 34, 550, 18, 17, 16, 549,
	13, 11, 10, 548, 12, 547, 546, 26, 545, 21,
	14, 29, 24, 544, 543, 19, 28, 25, 542, 9,
	541, 8, 7, 6, 5, 4, 540, 539, 2, 538,
	537, 0, 1, 536, 535, 534, 532, 15, 531, 432,
	83,
}
var yyR1 = [...]int{

	0, 1, 1, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 3, 12, 12, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 4, 5, 6, 18, 18, 7, 20,
	20, 21, 21, 21, 21, 21, 21, 21, 22, 22,
	23, 8, 24, 24, 25, 25, 25, 25, 25, 25,
	25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
	25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
	25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
	30, 30, 33, 33, 33, 33, 31, 31, 35, 35,
	26, 26, 32, 32, 36, 36, 36, 9, 37, 37,
	38, 38, 38, 38, 38, 38, 38, 29, 29, 39,
	39, 11, 42, 42, 43, 43, 43, 43, 10, 40,
	40, 44, 44, 44, 44, 39, 39, 39, 39, 39,
	39, 39, 39, 39, 39, 39, 39, 39, 39, 39,
	39, 39, 39, 49, 49, 50, 50, 50, 50, 50,
	50, 50, 50, 50, 51, 51, 56, 56, 56, 56,
	56, 56, 52, 52, 57, 57, 57, 57, 57, 57,
	57, 58, 58, 59, 59, 59, 59, 59, 53, 53,
	60, 60, 60, 60, 60, 60, 60, 62, 62, 61,
	61, 61, 61, 61, 61, 61, 54, 54, 63, 63,
	63, 63, 63, 63, 63, 63, 63, 63, 55, 55,
	64, 64, 64, 64, 64, 64, 46, 46, 46, 46,
	46, 46, 46, 46, 46, 46, 46, 46, 46, 47,
	47, 47, 47, 48, 48, 48, 27, 27, 28, 28,
	65, 65, 65, 65, 66, 66, 66, 14, 14, 68,
	16, 16, 69, 69, 69, 69, 69, 69, 17, 17,
	41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
	41, 41, 41, 41, 41, 41, 41, 19, 19, 19,
	19, 19, 70, 70, 70, 70, 70, 70, 67, 67,
	67, 15, 15, 15, 45, 45, 45, 34, 34, 34,
	34, 34, 34, 34,
}
var yyR2 = [...]int{

	0, 2, 1, 0, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 4, 2, 1, 0, 4, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 1, 4, 4, 4, 2, 1, 5, 2,
	1, 0, 1, 4, 2, 2, 2, 2, 2, 1,
	1, 5, 2, 1, 0, 1, 2, 1, 1, 2,
	2, 2, 4, 2, 2, 2, 1, 2, 2, 2,
	4, 4, 4, 2, 2, 2, 2, 2, 2, 1,
	4, 2, 4, 4, 1, 2, 2, 2, 2, 2,
	2, 1, 0, 2, 2, 2, 2, 1, 1, 2,
	2, 1, 2, 1, 0, 1, 3, 5, 2, 1,
	0, 2, 2, 2, 2, 2, 2, 2, 1, 2,
	1, 5, 2, 1, 0, 2, 2, 2, 5, 2,
	1, 0, 1, 2, 2, 0, 2, 2, 2, 2,
	2, 2, 2, 3, 6, 6, 2, 1, 1, 2,
	2, 2, 2, 2, 1, 0, 2, 1, 4, 4,
	4, 4, 4, 4, 2, 1, 0, 2, 2, 2,
	2, 2, 2, 1, 0, 4, 2, 2, 2, 2,
	2, 2, 1, 0, 2, 2, 2, 2, 2, 1,
	0, 1, 4, 2, 2, 2, 2, 2, 1, 0,
	2, 2, 2, 2, 2, 2, 2, 1, 0, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
	0, 2, 2, 2, 2, 1, 0, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
	1, 1, 1, 0, 1, 1, 2, 1, 2, 1,
	1, 2, 2, 2, 1, 2, 2, 2, 1, 1,
	2, 1, 0, 1, 1, 2, 2, 2, 2, 1,
	0, 2, 2, 2, 1, 1, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 0, 4, 4,
	4, 4, 0, 1, 1, 1, 1, 1, 0, 1,
	1, 0, 1, 1, 0, 1, 2, 0, 1, 1,
	1, 1, 1, 1,
}
var yyChk = [...]int{

	-1000, -1, -2, -3, -4, -5, -6, -7, -8, -9,
	-10, -11, 16, 31, 32, 33, 34, 36, 93, 101,
	100, -1, 14, 14, 14, 14, 6, 6, 6, -44,
	-45, 128, 35, -15, 8, 9, 6, -12, -13, 17,
	18, 25, 26, 27, 28, 19, 20, 21, 22, 23,
	24, 29, 30, -16, -69, -15, 10, 75, 68, 69,
	-17, -41, 76, 78, -15, 10, 79, 80, 81, 68,
	67, 82, 83, 69, 92, -18, -19, 77, 78, 14,
	14, 14, 14, 4, 6, 4, 14, 15, -12, 14,
	6, 7, 4, 4, 4, 4, -15, 6, 4, 6,
	6, 8, 9, 4, 15, -16, -15, 6, -70, 70,
	71, 72, 73, 74, 15, -17, -15, -15, 10, -15,
	-15, -15, 6, 6, 4, 6, 4, -70, -15, 10,
	15, -18, -15, 10, -15, 10, -20, -21, 6, 35,
	87, 88, 89, 91, -24, -25, 37, 38, 39, 40,
	41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
	51, 52, 53, 54, 57, 58, 59, 60, 61, 62,
	84, 85, 86, 87, 88, 89, 90, 91, -37, -38,
	94, 95, 96, 97, 98, 99, -40, -39, -41, 102,
	103, 104, 105, 106, 122, 123, 126, 127, 155, 156,
	157, 158, 159, 160, 161, -42, -43, -15, 11, 128,
	-14, -68, -34, 4, 6, 7, 12, -15, 10, 82,
	82, 82, 82, 15, -20, 14, 6, 6, 6, 6,
	15, -24, 4, 6, -15, -15, 14, 6, 6, 4,
	4, 4, 4, 14, 14, 14, 55, 56, 4, 4,
	4, 4, 14, 6, 14, 14, 6, 6, 6, 6,
	6, 15, -37, 6, 4, 4, 4, 4, 4, 15,
	-40, -17, 4, -46, 107, 108, 109, 110, 111, 112,
	113, 114, 115, 116, 117, 118, -47, 119, 120, 121,
	-46, -47, 4, -48, 124, 125, -15, -15, 6, 4,
	4, 6, 6, 15, -42, 4, 4, 4, 15, -14,
	4, 4, 4, 4, -22, -23, 6, -26, -15, -27,
	-65, -67, 67, 68, 75, -15, 10, -28, -66, -67,
	68, 75, -29, -39, -30, -33, 63, 64, -31, -35,
	6, 97, -32, -36, 6, 4, -45, 4, 15, -22,
	15, -26, 15, -27, 6, 6, -15, 15, -28, 6,
	-15, 15, -40, 15, -30, 65, 66, -34, 15, -31,
	4, 15, -32, 97, 14, 14, 4, -49, -50, 97,
	129, 130, 131, 132, 133, 134, 135, -49, 15, -49,
	4, 14, 14, 14, 14, 14, 14, 15, -51, -56,
	141, 140, 145, 151, 154, -52, -57, 136, 140, 141,
	153, 154, 151, -52, -53, -60, -61, 72, 151, 145,
	154, 146, 142, 141, 143, 144, 140, 128, -54, -63,
	142, 141, 143, 144, 140, 128, 145, 147, 148, -55,
	-64, 149, 150, 151, 152, 15, -51, 4, 4, 4,
	4, 4, 15, -52, 14, 4, 4, 4, 4, 4,
	15, 15, -53, 14, 4, 4, 4, 6, -15, 4,
	-15, 4, 4, 4, 15, -54, -15, 4, -15, 4,
	4, 4, 4, 6, 6, 15, -55, 6, 13, 4,
	4, -58, -59, 137, 138, 139, -62, -61, 15, -58,
	6, 13, 12, 4, 15, -62,
}
var yyDef = [...]int{

	3, -2, 2, 4, 5, 6, 7, 8, 9, 10,
	11, 12, 0, 0, 0, 0, 0, 0, 0, -2,
	0, 1, 16, 262, 270, 287, 0, 0, 0, 0,
	132, 0, 0, 305, 302, 303, 0, 0, 15, 0,
	0, 0, 0, 0, 0, 301, 0, 0, 0, 0,
	0, 0, 32, 0, 261, 263, 264, 301, 0, 292,
	0, 269, 301, 301, 274, 275, 301, 301, 301, 0,
	0, 0, 0, 292, 301, 0, 37, 301, 301, 41,
	54, 110, 135, 133, 134, 306, 124, 13, 14, 301,
	18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
	28, 29, 30, 31, 33, 260, 265, 266, 267, 293,
	294, 295, 296, 297, 34, 268, 271, 272, 273, 276,
	277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
	35, 36, 0, 0, 0, 0, 0, 40, 42, 0,
	0, 0, 0, 0, 0, 53, 55, 0, 57, 58,
	0, 301, 301, 0, 0, 0, 66, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 79, 0,
	0, 0, 84, 0, 0, 0, 0, 0, 0, 109,
	0, 0, 0, 0, 0, 0, 0, 130, 120, 0,
	226, 239, 226, 239, 0, 243, 301, 301, 0, 147,
	148, 0, 0, 0, 0, 0, -2, 0, 0, 0,
	0, 258, 259, 308, 309, 310, 311, 312, 313, 0,
	0, 0, 0, 38, 39, 0, 44, 45, 46, 47,
	51, 52, 56, 59, 60, 61, 301, 63, 64, 65,
	67, 68, 69, 298, 298, 135, 73, 74, 75, 76,
	77, 78, 92, 81, 0, 104, 85, 86, 87, 88,
	89, 107, 108, 111, 112, 113, 114, 115, 116, 128,
	129, 119, 136, 137, 227, 228, 229, 230, 231, 232,
	233, 234, 235, 236, 237, 238, 138, 240, 241, 242,
	139, 140, 141, 142, 244, 245, 0, 301, 146, 149,
	150, 151, 152, 121, 122, 125, 126, 127, 17, 257,
	288, 290, 289, 291, 0, 49, 50, 0, 101, 0,
	247, 250, 0, 0, 301, 299, 300, 0, 249, 254,
	0, 301, 0, 118, 0, 91, 0, 301, 0, 97,
	98, 0, 0, 103, 105, 143, 0, 0, 43, 48,
	62, 100, 70, 246, 251, 252, 253, 71, 248, 255,
	256, 72, 117, 80, 90, 93, 94, 95, 82, 96,
	99, 83, 102, 0, 155, 155, 106, 0, 154, 0,
	157, 0, 0, 0, 0, 0, 0, 0, 144, 153,
	156, 166, 174, 174, 190, 208, 220, 145, 0, 165,
	0, 0, 0, 0, 0, 0, 173, 0, 0, 0,
	0, 0, 0, 0, 0, 189, 191, 0, 0, 0,
	0, 0, 301, 0, 301, 0, 0, 0, 0, 207,
	301, 0, 301, 0, 0, 0, 0, 0, 0, 0,
	219, 0, 0, 0, 225, 158, 164, 167, 168, 169,
	170, 171, 159, 172, 183, 176, 177, 178, 179, 180,
	160, 161, 188, 199, 193, 194, 195, 196, 200, 201,
	202, 203, 204, 205, 162, 206, 209, 210, 211, 212,
	213, 214, 215, 216, 217, 163, 218, 221, 222, 223,
	224, 0, 182, 0, 0, 0, 0, 198, 175, 181,
	184, 185, 186, 187, 192, 197,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
	122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
	132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
	142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
	152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:29
		{
		}
	case 3:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:31
		{
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:32
		{
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:33
		{
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:34
		{
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:35
		{
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:36
		{
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:37
		{
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:38
		{
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:39
		{
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:40
		{
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:47
		{
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:48
		{
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:49
		{
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:50
		{
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:51
		{
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:52
		{
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:53
		{
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:54
		{
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:55
		{
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:56
		{
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:57
		{
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:58
		{
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:59
		{
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:60
		{
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:61
		{
		}
	case 41:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:76
		{
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:77
		{
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:78
		{
		}
	case 44:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:79
		{
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:80
		{
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:81
		{
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:82
		{
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:84
		{
		}
	case 54:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:92
		{
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:93
		{
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:94
		{
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:95
		{
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:96
		{
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:97
		{
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:98
		{
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:99
		{
		}
	case 62:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:100
		{
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:101
		{
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:102
		{
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:103
		{
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:105
		{
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:106
		{
		}
	case 69:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:107
		{
		}
	case 73:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:111
		{
		}
	case 74:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:112
		{
		}
	case 75:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:113
		{
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:114
		{
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:115
		{
		}
	case 78:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:116
		{
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:117
		{
		}
	case 80:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:118
		{
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:119
		{
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:120
		{
		}
	case 83:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:121
		{
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:122
		{
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:123
		{
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:124
		{
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:125
		{
		}
	case 88:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:126
		{
		}
	case 89:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:127
		{
		}
	case 92:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:131
		{
		}
	case 93:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:132
		{
		}
	case 94:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:133
		{
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:134
		{
		}
	case 99:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:139
		{
		}
	case 104:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:145
		{
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:146
		{
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.go.y:147
		{
		}
	case 110:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:153
		{
		}
	case 111:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:154
		{
		}
	case 112:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:155
		{
		}
	case 113:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:156
		{
		}
	case 114:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:157
		{
		}
	case 115:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:158
		{
		}
	case 116:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:159
		{
		}
	case 124:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:169
		{
		}
	case 125:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:170
		{
		}
	case 126:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:171
		{
		}
	case 127:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:172
		{
		}
	case 133:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:180
		{
		}
	case 134:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:181
		{
		}
	case 135:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:183
		{
		}
	case 136:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:184
		{
		}
	case 137:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:185
		{
		}
	case 138:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:186
		{
		}
	case 139:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:187
		{
		}
	case 140:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:188
		{
		}
	case 141:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:189
		{
		}
	case 142:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:190
		{
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.go.y:191
		{
		}
	case 146:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:194
		{
		}
	case 149:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:197
		{
		}
	case 150:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:198
		{
		}
	case 151:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:199
		{
		}
	case 152:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:200
		{
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:202
		{
		}
	case 155:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:204
		{
		}
	case 156:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:205
		{
		}
	case 157:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:206
		{
		}
	case 158:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:207
		{
		}
	case 159:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:208
		{
		}
	case 160:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:209
		{
		}
	case 161:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:210
		{
		}
	case 162:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:211
		{
		}
	case 163:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:212
		{
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:214
		{
		}
	case 166:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:216
		{
		}
	case 167:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:217
		{
		}
	case 168:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:218
		{
		}
	case 169:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:219
		{
		}
	case 170:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:220
		{
		}
	case 171:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:221
		{
		}
	case 173:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:223
		{
		}
	case 174:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:225
		{
		}
	case 175:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.go.y:226
		{
		}
	case 176:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:227
		{
		}
	case 177:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:228
		{
		}
	case 178:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:229
		{
		}
	case 179:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:230
		{
		}
	case 180:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:231
		{
		}
	case 182:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:233
		{
		}
	case 183:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:235
		{
		}
	case 184:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:236
		{
		}
	case 185:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:237
		{
		}
	case 186:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:238
		{
		}
	case 187:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:239
		{
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:241
		{
		}
	case 190:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:243
		{
		}
	case 191:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:244
		{
		}
	case 198:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:251
		{
		}
	case 199:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:253
		{
		}
	case 200:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:254
		{
		}
	case 201:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:255
		{
		}
	case 202:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:256
		{
		}
	case 203:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:257
		{
		}
	case 204:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:258
		{
		}
	case 205:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:259
		{
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:261
		{
		}
	case 208:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:263
		{
		}
	case 209:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:264
		{
		}
	case 210:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:265
		{
		}
	case 211:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:266
		{
		}
	case 212:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:267
		{
		}
	case 213:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:268
		{
		}
	case 214:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:269
		{
		}
	case 215:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:270
		{
		}
	case 216:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:271
		{
		}
	case 217:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:272
		{
		}
	case 219:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:274
		{
		}
	case 220:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:276
		{
		}
	case 221:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:277
		{
		}
	case 222:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:278
		{
		}
	case 223:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:279
		{
		}
	case 224:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:280
		{
		}
	case 225:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:281
		{
		}
	case 226:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:283
		{
		}
	case 227:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:284
		{
		}
	case 228:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:285
		{
		}
	case 229:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:286
		{
		}
	case 230:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:287
		{
		}
	case 231:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:288
		{
		}
	case 232:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:289
		{
		}
	case 233:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:290
		{
		}
	case 234:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:291
		{
		}
	case 235:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:292
		{
		}
	case 236:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:293
		{
		}
	case 237:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:294
		{
		}
	case 238:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:295
		{
		}
	case 239:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:297
		{
		}
	case 240:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:298
		{
		}
	case 241:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:299
		{
		}
	case 242:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:300
		{
		}
	case 243:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:302
		{
		}
	case 244:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:303
		{
		}
	case 245:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:304
		{
		}
	case 247:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:306
		{
		}
	case 249:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:308
		{
		}
	case 250:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:310
		{
		}
	case 251:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:311
		{
		}
	case 252:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:312
		{
		}
	case 253:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:313
		{
		}
	case 254:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:315
		{
		}
	case 255:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:316
		{
		}
	case 256:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.go.y:317
		{
		}
	case 258:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:319
		{
		}
	case 259:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.go.y:321
		{
		}
	case 262:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:325
		{
		}
	case 270:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:334
		{
		}
	case 287:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:352
		{
		}
	case 292:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:358
		{
		}
	case 298:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:365
		{
		}
	case 301:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:369
		{
		}
	case 304:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:373
		{
		}
	case 307:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.go.y:377
		{
		}
	}
	goto yystack /* stack new state and value */
}
